name: Docker
on:
  workflow_dispatch: 
  push:
    branches: ['main']
    paths: ['Dockerfile']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: 'Install pivnet CLI'
        run: |
          wget -nv -O pivnet https://github.com/pivotal-cf/pivnet-cli/releases/download/v3.0.1/pivnet-linux-amd64-3.0.1
          chmod +x pivnet
          sudo mv pivnet /usr/local/bin
          pivnet version
      
      - name: 'Download Tanzu CLI and extensions'
        env:
          API_TOKEN: ${{ secrets.TANZUNET_REFRESH_TOKEN }}
        run: |
          pivnet login --api-token $API_TOKEN
          # tanzu-app-accelerator-*.vsix
          pivnet download-product-files --product-slug='tanzu-application-platform' --release-version='1.6.1' --product-file-id=1443264
          mv $(find . -name 'tanzu-app-accelerator-*' -print0) tanzu-app-accelerator.vsix
          # tanzu-vscode-extension-*.vsix
          pivnet download-product-files --product-slug='tanzu-application-platform' --release-version='1.6.1' --product-file-id=1538659
          mv $(find . -name 'tanzu-vscode-extension-*' -print0) tanzu-vscode-extension.vsix
          # tanzu-cli-linux-amd64*.tar

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Log into Tanzu Network
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: registry.tanzu.vmware.com
          username: ${{ secrets.TANZUNET_USERNAME }}
          password: ${{ secrets.TANZUNET_PASSWORD }}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}